baseURL = 'https://jinchenglee.github.io/'
languageCode = 'en-us'
title = "Vitob's Blog Site"
theme = 'hugo-ficurinia'
imagePreview = 'true'

[markup]
  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 4
